// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.9
// source: miniusercenter/v1/errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_UserAlreadyExist ErrorReason = 0
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "UserAlreadyExist",
	}
	ErrorReason_value = map[string]int32{
		"UserAlreadyExist": 0,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_miniusercenter_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_miniusercenter_v1_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_miniusercenter_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_miniusercenter_v1_errors_proto protoreflect.FileDescriptor

var file_miniusercenter_v1_errors_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6d, 0x69, 0x6e, 0x69, 0x75, 0x73, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x6d, 0x69, 0x6e, 0x69, 0x75, 0x73, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2a, 0x23, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x00, 0x42, 0x55, 0x5a, 0x53, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x70, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x6a,
	0x2f, 0x73, 0x75, 0x70, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x6a, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x75, 0x73, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x75,
	0x73, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_miniusercenter_v1_errors_proto_rawDescOnce sync.Once
	file_miniusercenter_v1_errors_proto_rawDescData = file_miniusercenter_v1_errors_proto_rawDesc
)

func file_miniusercenter_v1_errors_proto_rawDescGZIP() []byte {
	file_miniusercenter_v1_errors_proto_rawDescOnce.Do(func() {
		file_miniusercenter_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_miniusercenter_v1_errors_proto_rawDescData)
	})
	return file_miniusercenter_v1_errors_proto_rawDescData
}

var file_miniusercenter_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_miniusercenter_v1_errors_proto_goTypes = []interface{}{
	(ErrorReason)(0), // 0: miniusercenter.v1.ErrorReason
}
var file_miniusercenter_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_miniusercenter_v1_errors_proto_init() }
func file_miniusercenter_v1_errors_proto_init() {
	if File_miniusercenter_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_miniusercenter_v1_errors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_miniusercenter_v1_errors_proto_goTypes,
		DependencyIndexes: file_miniusercenter_v1_errors_proto_depIdxs,
		EnumInfos:         file_miniusercenter_v1_errors_proto_enumTypes,
	}.Build()
	File_miniusercenter_v1_errors_proto = out.File
	file_miniusercenter_v1_errors_proto_rawDesc = nil
	file_miniusercenter_v1_errors_proto_goTypes = nil
	file_miniusercenter_v1_errors_proto_depIdxs = nil
}
