// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// initApp 声明 injector 的函数签名
func initApp() (*UserCenterService, func(), error) {
	db, cleanup, err := NewDB()
	if err != nil {
		return nil, nil, err
	}
	mainDatastore := NewStore(db)
	mainBiz := NewBiz(mainDatastore)
	userCenterService := NewUserCenterService(mainBiz)
	return userCenterService, func() {
		cleanup()
	}, nil
}
