// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

// initApp 声明 injector 的函数签名
func initApp(db *gorm.DB) *UserCenterService {
	dataStoreWrapper := NewDataStoreWrapper(db)
	mainDatastore := dataStoreWrapper.ds
	mainBiz := NewBiz(mainDatastore)
	userCenterService := NewUserCenterService(mainBiz)
	return userCenterService
}
