server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  db:
    addr: 127.0.0.1:3306
    username: zero
    password: zero(#)666
    database: zero
