// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"os"
)

// Injectors from wire.go:

// initApp 声明 injector 的函数签名
func initApp(db *gorm.DB) *UserCenterService {
	mainDatastore := NewStore(db)
	mainBiz := NewBiz(mainDatastore)
	int2 := _wireIntValue
	reader := _wireFileValue
	userCenterService := &UserCenterService{
		biz:    mainBiz,
		quota:  int2,
		reader: reader,
	}
	return userCenterService
}

var (
	_wireIntValue  = 10
	_wireFileValue = os.Stdin
)
